vich_uploader:
    db_driver: orm
    mappings:
        image:
            uri_prefix:         /images/images
            upload_destination: '%kernel.project_dir%/public/images/images'
            namer:              vich_uploader.namer_uniqid
            directory_namer: ~
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
#        client_gray_scale:
#            uri_prefix:         /uploads/images/real_property
#            upload_destination: '%kernel.project_dir%/public/uploads/images/real_property'
#            namer:              vich_uploader.namer_uniqid
#            directory_namer: ~
#            delete_on_remove: true
#            delete_on_update: true
#            inject_on_load: true
