<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[2].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Form\\Platform\\ContainerImageType' => function () {
    return ($this->privates['App\Form\Platform\ContainerImageType'] ?? $this->privates['App\Form\Platform\ContainerImageType'] = new \App\Form\Platform\ContainerImageType());
}, 'App\\Form\\Platform\\ContainerType' => function () {
    return ($this->privates['App\Form\Platform\ContainerType'] ?? $this->privates['App\Form\Platform\ContainerType'] = new \App\Form\Platform\ContainerType());
}, 'App\\Form\\Platform\\ImageType' => function () {
    return ($this->privates['App\Form\Platform\ImageType'] ?? $this->privates['App\Form\Platform\ImageType'] = new \App\Form\Platform\ImageType());
}, 'App\\Form\\Platform\\RegistrationType' => function () {
    return ($this->privates['App\Form\Platform\RegistrationType'] ?? $this->privates['App\Form\Platform\RegistrationType'] = new \App\Form\Platform\RegistrationType());
}, 'App\\Form\\RealProperty\\RealPropertyImageType' => function () {
    return ($this->privates['App\Form\RealProperty\RealPropertyImageType'] ?? $this->privates['App\Form\RealProperty\RealPropertyImageType'] = new \App\Form\RealProperty\RealPropertyImageType());
}, 'App\\Form\\RealProperty\\RealPropertyType' => function () {
    return ($this->privates['App\Form\RealProperty\RealPropertyType'] ?? $this->privates['App\Form\RealProperty\RealPropertyType'] = new \App\Form\RealProperty\RealPropertyType());
}, 'App\\Form\\RealProperty\\RealPropertyTypeType' => function () {
    return ($this->privates['App\Form\RealProperty\RealPropertyTypeType'] ?? $this->privates['App\Form\RealProperty\RealPropertyTypeType'] = new \App\Form\RealProperty\RealPropertyTypeType());
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load(__DIR__.'/getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load(__DIR__.'/getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load(__DIR__.'/getForm_Type_FormService.php'));
}, 'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => function () {
    return ($this->services['vich_uploader.form.type.file'] ?? $this->load(__DIR__.'/getVichUploader_Form_Type_FileService.php'));
}, 'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => function () {
    return ($this->services['vich_uploader.form.type.image'] ?? $this->load(__DIR__.'/getVichUploader_Form_Type_ImageService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load(__DIR__.'/getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 1 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load(__DIR__.'/getForm_TypeExtension_Upload_ValidatorService.php'));
}, 2), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? $this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? $this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load(__DIR__.'/getForm_TypeGuesser_DoctrineService.php'));
}, 1))), ($this->privates['form.resolved_type_factory'] ?? $this->privates['form.resolved_type_factory'] = new \Symfony\Component\Form\ResolvedFormTypeFactory()));
