<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP0S9Qc1\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP0S9Qc1/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP0S9Qc1.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP0S9Qc1\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerP0S9Qc1\srcDebugProjectContainer(array(
    'container.build_hash' => 'P0S9Qc1',
    'container.build_id' => '552d9f37',
    'container.build_time' => 1515508596,
));
