<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[2].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/Command/DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load(__DIR__.'/getForm_RegistryService.php')), array(0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Form\\Platform', 2 => 'App\\Form\\RealProperty', 3 => 'Symfony\\Bridge\\Doctrine\\Form\\Type', 4 => 'Vich\\UploaderBundle\\Form\\Type'), array(0 => 'App\\Form\\Platform\\ImageType', 1 => 'App\\Form\\Platform\\RegistrationType', 2 => 'App\\Form\\RealProperty\\RealPropertyType', 3 => 'App\\Form\\RealProperty\\RealPropertyTypeType', 4 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 5 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 6 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType', 7 => 'Vich\\UploaderBundle\\Form\\Type\\VichFileType', 8 => 'Vich\\UploaderBundle\\Form\\Type\\VichImageType'), array(0 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 1 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension'), array(0 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser'));

$instance->setName('debug:form');

return $instance;
