<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Platform\RegistrationType' shared autowired service.

include_once $this->targetDirs[2].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[2].'/src/Form/Platform/RegistrationType.php';

return $this->privates['App\Form\Platform\RegistrationType'] = new \App\Form\Platform\RegistrationType();
