<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\RealProperty\RealPropertyTypeType' shared autowired service.

include_once $this->targetDirs[2].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[2].'/src/Form/RealProperty/RealPropertyTypeType.php';

return $this->privates['App\Form\RealProperty\RealPropertyTypeType'] = new \App\Form\RealProperty\RealPropertyTypeType();
