<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Platform\SecurityController' shared autowired service.

include_once $this->targetDirs[2].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[2].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[2].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[2].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[2].'/src/Controller/Platform/SecurityController.php';

return $this->services['App\Controller\Platform\SecurityController'] = new \App\Controller\Platform\SecurityController();
